FROM openjdk:latest

WORKDIR /app/merchantguid

COPY ./src /app/merchantguid

RUN javac G:\Amaap\MerchentGuide\MerchantGuide\src\main\java\com\amaap\merchentguide\Main.java

CMD ["java", "-cp", "src", "Main"]